include ../makenext.mk

default:
	@ printf "make $(OK_COLOUR)test            ${COMMENT_COLOUR}This a test${NO_COLOUR}\n"
	@ printf "make $(OK_COLOUR)another-test    ${COMMENT_COLOUR}This another test${NO_COLOUR}\n"

test:
	@ echo "$(ERROR_COLOUR)This $(WARN_COLOUR)is $(OK_COLOUR)a $(NO_COLOUR)test."

another-test:
	@ echo "$(COMMENT_COLOUR)This another test."
